# Generated by Django 5.1.6 on 2025-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('instuctor', models.CharField(max_length=100)),
            ],
        ),
    ]
