# Generated by Django 5.1.6 on 2025-03-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instuctor',
            new_name='instructor',
        ),
    ]
